[package]
name = "rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cooked-waker = { path = "../cooked-waker" }
crossbeam = "0.8.4"
futures = "*"
pin-project-lite = "0.2.14"
snowflake = "1.3.0"
